import '@/styles/globals.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <script src="https://cdn.tailwindcss.com"></script>
      </head>
      <body>
        <header className="bg-blue-500 text-white py-4 text-center">
          <h1 className="text-3xl font-bold">Next Photo Album</h1>
        </header>
        {children}
        <footer className="bg-gray-800 text-white py-4 text-center">
          <p className="text-sm">Created by Augusto Zangrando</p>
        </footer>
      </body>
    </html>
  )
}
